const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{tilemap: 0},
	{janela: 0},
	{Sprite2: 0},
	{Solid: 0},
	{plataforma: 0},
	{Flash: 0},
	{bau: 0},
	{Platform: 0},
	{caixa: 0},
	{porta: 0},
	{chave: 0},
	{bomba: 0},
	{ScrollTo: 0},
	{jogador: 0},
	{chao: 0},
	{Keyboard: 0},
	{direcao: 0},
	{porco_patrulheiro: 0},
	{sensorPatru_direita: 0},
	{sensorPatru_esquerda: 0},
	{porco_canhao: 0},
	{canhao: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Rotate: 0},
	{bala: 0},
	{sensorCanhao: 0},
	{vida_hud: 0},
	{itens_hud: 0},
	{black_blackground: 0},
	{jogador_dialogo: 0},
	{SpriteFont: 0},
	{Sprite: 0},
	{chefao: 0},
	{Audio: 0},
	{arteMenu: 0},
	{Text: 0},
	{SpriteFont2: 0},
	{BTN: 0},
	{LOGO: 0},
	{btnVisual: 0},
	{Tilemap2: 0},
	{TiledBackground: 0},
	{nuvem: 0},
	{tilemap3: 0},
	{passarDeFase: 0},
	{morte: 0},
	{btnTryAgain: 0},
	{btnmenu: 0},
	{gameoverfont: 0},
	{TiledBackground2: 0},
	{SpriteFont3: 0},
	{btnconcluido: 0},
	{Sprite3: 0},
	{voltar: 0},
	{SpriteFont4: 0},
	{historia: 0},
	{vidas: 0},
	{vidas2: 0}
];

self.InstanceType = {
	tilemap: class extends self.ITilemapInstance {},
	janela: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	plataforma: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	chao: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	porco_patrulheiro: class extends self.ISpriteInstance {},
	sensorPatru_direita: class extends self.ISpriteInstance {},
	sensorPatru_esquerda: class extends self.ISpriteInstance {},
	porco_canhao: class extends self.ISpriteInstance {},
	canhao: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	sensorCanhao: class extends self.ISpriteInstance {},
	vida_hud: class extends self.ISpriteInstance {},
	itens_hud: class extends self.ISpriteInstance {},
	black_blackground: class extends self.ISpriteInstance {},
	jogador_dialogo: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	chefao: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	arteMenu: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	BTN: class extends self.IButtonInstance {},
	LOGO: class extends self.ISpriteInstance {},
	btnVisual: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	nuvem: class extends self.ISpriteInstance {},
	tilemap3: class extends self.ITilemapInstance {},
	passarDeFase: class extends self.ISpriteInstance {},
	morte: class extends self.ISpriteInstance {},
	btnTryAgain: class extends self.IButtonInstance {},
	btnmenu: class extends self.IButtonInstance {},
	gameoverfont: class extends self.ISpriteFontInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	btnconcluido: class extends self.IButtonInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	voltar: class extends self.IButtonInstance {},
	SpriteFont4: class extends self.ISpriteFontInstance {},
	historia: class extends self.IButtonInstance {}
}